### ISSUE TITLE
Create constants files for missing Ember organizations

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-help-wanted-server#32]
## Description

Currently, the client and server apps for [Help Wanted](https://help-wanted.emberjs.com/) site have filters that somewhat arbitrarily combine repos and issues from different GitHub organizations. The end user, unless they looked at the server app code, may be confused when a filter doesn't work the way that they expected to.

## Problem

The [config file](https://github.com/ember-learn/ember-help-wanted-server/blob/2335d5536af1bbf841a3a701d0b4ad657367bbf2/src/config.js) lists 10 organizations. We have already searched and cached issues from these organizations.

There are also [constants files](https://github.com/ember-learn/ember-help-wanted-server/tree/2335d5536af1bbf841a3a701d0b4ad657367bbf2/src/constants/ember-organizations). Each file gets to define which issues will end up making to the client app when the end user applies a filter. (By default, we show issues from all repos in an organization, that have added a supported label.)

We need to add 6 more constants files for these organizations:

- `ember-a11y`
- `ember-data`
- `ember-engines`
- `ember-template-lint`
- `empress`
- `typed-ember`

## TODOs

- [ ] Study an existing constants file to learn how to use `GithubOrganization` class. Note that the array elements in `repositoryNames` and `supportedLabels` have been alphabetized to help with code maintenance.

- [ ] Create 6 constants files, one for each organization listed above.

- [ ] Create 6 test files in `test/constants/ember-organizations` directory. The tests help assert that you instantiated the `GithubOrganization` class correctly.

## Notes

To quickly enumerate all repos in an organization, use the GitHub API:

```bash
# Find all repos in ember-cli (page 1)
https://api.github.com/orgs/ember-cli/repos?per_page=100&page=1
```

You can visit the link a browser, copy-paste the response (an array of POJOs), then extract an array of repo names.

**Comment by ijlee2** [comment]
Related issue for the client app: https://github.com/ember-learn/ember-help-wanted/issues/174

**Comment by neojp** [comment]
@ijlee2 I have committed the code e599468 & sent a PR #33. Please take a look at them. I'm not 100% sure this is correct, but I followed the rest of the code as much as possible.

One thing that got me curious is that the constants tests require you to compare the filters count coming from the GitHub API. Wouldn't the tests fail if someone adds additional labels in repos?
