### ISSUE TITLE
Allow returning issues from more organizations

### ISSUE THREAD

**Issue by ijlee2** [ember-learn/ember-help-wanted-server#34]
## Problem

In #32, we created 6 constants files that list all issues and labels that a GitHub organization will have. Let's now connect these constants files to the API endpoint.

## TODOs

- [ ] In `src/utils/get-repos-with-supported-labels.js`, update the variable `mapGroupNameToRepositories` as follows:

    ```javascript
    const mapGroupNameToRepositories = new Map([
      // GitHub organizations
      ['adopted-ember-addons', adopted_ember_addons],
      ['ember-a11y', ember_a11y],
      ['ember-cli', ember_cli],
      ['ember-data', ember_data],
      ['ember-engines', ember_engines],
      ['ember-learn', ember_learn],
      ['ember-template-lint', ember_template_lint],
      ['emberjs', emberjs],
      ['empress', empress],
      ['typed-ember', typed_ember],

      // Custom categories
      ['RFCs', rfcs],
    ]);
    ```

    Note, the Map instance's key names match the filter names defined in the [client app](https://github.com/ember-learn/ember-help-wanted/issues/174).

- [ ] Complete the `get-repos-with-supported-labels.js` file by defining the variables `adopted_ember_addons`, `ember_a11y`, ..., `rfcs` mentioned above. The idea is, each variable (with the exception of `rfcs`, which stays as is) corresponds to the exported object from the constants file.

    ```javascript
    const adopted_ember_addons = require('../constants/ember-organizations/adopted-ember-addons');
    const ember_cli = require('../constants/ember-organizations/ember-cli');
    const ember_learn = require('../constants/ember-organizations/ember-learn');
    const emberjs = require('../constants/ember-organizations/emberjs');
    ```
- [ ] Some tests in `test/utils/get-repos-with-supported-labels.js` may start to fail. Without changing the fixture file, update the assertions to match the expected results.

**Comment by ijlee2** [comment]
Completed in #35 .
